This script will calculate the three top 10 best and worst dishes for model 22 Three tables will be presented with absolute error for the first, percentage error for the second and percentage error after removal of dishes with a ground truth value of under 5g.

Imports and paths

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 180)

MODEL22_DIR = Path("/content/drive/MyDrive/Speciale/Models/Model_22_Carbohydrate_estimator_plus_ingredient_estimator")

fixed_csv_path = MODEL22_DIR / "model22_test_predictions_FIXED.csv"

df = pd.read_csv(fixed_csv_path)

print("Loaded fixed prediction CSV:")
print(fixed_csv_path)
print("Shape:", df.shape)

display(df.head())
print(df.columns.tolist())

Loaded fixed prediction CSV:
/content/drive/MyDrive/Speciale/Models/Model_22_Carbohydrate_estimator_plus_ingredient_estimator/model22_test_predictions_FIXED.csv
Shape: (507, 215)

,dish_id,total_carb,split,source_cafe,rgb_carb_pred,pred_ingr_almonds,pred_ingr_apple,pred_ingr_artichokes,pred_ingr_arugula,pred_ingr_asparagus,pred_ingr_avocado,pred_ingr_baby_carrots,pred_ingr_bacon,pred_ingr_bagels,pred_ingr_banana_with_peel,pred_ingr_basil,pred_ingr_beef,pred_ingr_beets,pred_ingr_bell_peppers,pred_ingr_berries,pred_ingr_black_beans,pred_ingr_blackberries,pred_ingr_blue_cheese,pred_ingr_blueberries,pred_ingr_bok_choy,pred_ingr_bread,pred_ingr_broccoli,pred_ingr_brown_rice,pred_ingr_brown_sugar,pred_ingr_brownies,pred_ingr_brussels_sprouts,pred_ingr_bulgur,pred_ingr_butter,pred_ingr_buttermilk,pred_ingr_cabbage,pred_ingr_caesar_dressing,pred_ingr_caesar_salad,pred_ingr_cantaloupe,pred_ingr_carrot,pred_ingr_cauliflower,pred_ingr_celery,pred_ingr_celery_root,pred_ingr_cereal,pred_ingr_chard,pred_ingr_chayote_squash,pred_ingr_cheese,pred_ingr_cheese_pizza,pred_ingr_cherry_tomatoes,pred_ingr_chia_seeds,pred_ingr_chicken,pred_ingr_chicken_apple_sausage,pred_ingr_chicken_breast,pred_ingr_chicken_salad,pred_ingr_chicken_thighs,pred_ingr_chickpeas,pred_ingr_chilaquiles,pred_ingr_chili,pred_ingr_chive,pred_ingr_cilantro,pred_ingr_cod,pred_ingr_cookies,pred_ingr_corn,pred_ingr_corn_on_the_cob,pred_ingr_cottage_cheese,pred_ingr_country_rice,pred_ingr_couscous,pred_ingr_cranberries,pred_ingr_cream,pred_ingr_cream_cheese,pred_ingr_croutons,pred_ingr_cucumbers,pred_ingr_deprecated,pred_ingr_egg_whites,pred_ingr_eggplant,pred_ingr_eggs,pred_ingr_feta_cheese,pred_ingr_figs,pred_ingr_fish,pred_ingr_flour,pred_ingr_fried_rice,pred_ingr_frozen_yogurt,pred_ingr_fruit_salad,pred_ingr_garden_salad,pred_ingr_garlic,pred_ingr_ginger,pred_ingr_goat_cheese,pred_ingr_granola,pred_ingr_grapefruit_juice,pred_ingr_grapes,pred_ingr_greek_salad,pred_ingr_greek_yogurt,pred_ingr_green_beans,pred_ingr_green_onions,pred_ingr_grilled_chicken,pred_ingr_ground_turkey,pred_ingr_hash_browns,pred_ingr_hominy,pred_ingr_honeydew_melons,pred_ingr_ice_cream_cones,pred_ingr_jalapenos,pred_ingr_jicama,pred_ingr_kale,pred_ingr_ketchup,pred_ingr_kimchi,pred_ingr_lemon_juice,pred_ingr_lentils,pred_ingr_lettuce,pred_ingr_lime,pred_ingr_mandarin_oranges,pred_ingr_mangos,pred_ingr_mayonnaise,pred_ingr_milk,pred_ingr_millet,pred_ingr_mixed_greens,pred_ingr_mozzarella_cheese,pred_ingr_mushroom,pred_ingr_mustard,pred_ingr_mustard_greens,pred_ingr_nopales,pred_ingr_oatmeal,pred_ingr_olive_oil,pred_ingr_olives,pred_ingr_onions,pred_ingr_orange,pred_ingr_orange_juice,pred_ingr_orange_with_peel,pred_ingr_oregano,pred_ingr_parmesan_cheese,pred_ingr_parsley,pred_ingr_parsnips,pred_ingr_pasta,pred_ingr_pasta_salad,pred_ingr_pears,pred_ingr_pecans,pred_ingr_pepper,pred_ingr_pepperoni,pred_ingr_pepperoni_pizza,pred_ingr_pesto,pred_ingr_pickles,pred_ingr_pilaf,pred_ingr_pineapple,pred_ingr_pizza,pred_ingr_plate_only,pred_ingr_pork,pred_ingr_potatoes,pred_ingr_pumpkin_seeds,pred_ingr_quinoa,pred_ingr_radishes,pred_ingr_raisins,pred_ingr_raspberries,pred_ingr_rice_noodles,pred_ingr_roasted_potatoes,pred_ingr_rosemary,pred_ingr_salmon,pred_ingr_salsa,pred_ingr_salt,pred_ingr_sandwiches,pred_ingr_sausage,pred_ingr_scrambled_eggs,pred_ingr_shallots,pred_ingr_snow_peas,pred_ingr_sour_cream,pred_ingr_soy_sauce,pred_ingr_spinach_cooked,pred_ingr_spinach_raw,pred_ingr_squash,pred_ingr_steak,pred_ingr_strawberries,pred_ingr_succotash,pred_ingr_sugar,pred_ingr_sun_dried_tomatoes,pred_ingr_sunflower_seeds,pred_ingr_sweet_potato,pred_ingr_syrup,pred_ingr_tatsoi,pred_ingr_tempeh,pred_ingr_thyme,pred_ingr_toast,pred_ingr_tofu,pred_ingr_tomatillo,pred_ingr_tomatoes,pred_ingr_tortilla,pred_ingr_tortilla_chips,pred_ingr_tuna,pred_ingr_tuna_salad,pred_ingr_turkey_bacon,pred_ingr_turnips,pred_ingr_vegetable_oil,pred_ingr_vinaigrette,pred_ingr_vinegar,pred_ingr_waffles,pred_ingr_walnuts,pred_ingr_watermelon,pred_ingr_wheat_berry,pred_ingr_wheat_bread,pred_ingr_white_beans,pred_ingr_white_rice,pred_ingr_white_wine,pred_ingr_wild_rice,pred_ingr_wine,pred_ingr_yam,pred_ingr_yogurt,pred_ingr_zucchini,rgb_only_pred,model22_pred,final_pred,abs_error,abs_error_rgb_only,old_final_pred_wrong,old_abs_error_wrong,abs_error_model22,squared_error_rgb_only,squared_error_model22,abs_error_improvement_model22_vs_rgb,squared_error_improvement_model22_vs_rgb
0,dish_1556575327,10.618,test,cafe1,12.507236,0.009016,0.000126,0.000004,2.917965e-07,0.000008,0.000081,1.070877e-11,0.000011,0.000009,1.198184e-08,5.233539e-09,7.546512e-08,1.566582e-08,0.000338,0.000002,2.406912e-06,0.000023,1.458003e-11,1.963233e-08,0.000160,2.284175e-10,0.000046,1.002613e-07,0.000001,2.210161e-09,9.972315e-01,3.778560e-09,5.991327e-09,3.637106e-09,9.756832e-07,1.755870e-05,0.001069,0.000008,9.599463e-04,0.000353,0.834086,1.250212e-09,2.663528e-09,0.000006,0.000108,1.115985e-06,0.000090,6.320483e-03,5.092313e-07,0.000181,0.001403,2.571360e-08,0.000180,0.000002,0.000235,1.557953e-06,1.256893e-07,7.208571e-07,3.535634e-07,1.518525e-06,3.758895e-08,1.351640e-08,0.000004,7.346235e-08,5.431486e-08,6.293493e-07,1.762673e-08,1.899649e-09,4.928183e-07,2.513159e-06,1.368159e-03,0.000057,4.004827e-08,0.000735,0.000003,7.402013e-06,1.811583e-09,0.000004,3.516791e-08,0.000006,1.465818e-08,1.674214e-09,2.838987e-08,0.000048,3.693335e-07,1.883570e-08,1.617868e-05,1.022961e-08,0.029716,1.530657e-08,3.817244e-08,1.280179e-05,2.421404e-08,2.972857e-05,1.229384e-09,0.000057,6.253964e-08,0.000146,2.585435e-08,2.592618e-05,1.833955e-10,0.000056,4.305515e-10,0.000755,2.944133e-05,2.203705e-08,5.024663e-06,1.758053e-06,2.850400e-06,5.824864e-09,2.427931e-06,1.940602e-07,2.049408e-06,0.000377,1.674933e-08,0.012802,5.704082e-08,1.372336e-06,4.070719e-12,3.213437e-08,0.001741,0.945412,0.000131,0.000026,2.655468e-09,5.970647e-08,4.047713e-10,7.612171e-05,5.763829e-05,3.708603e-12,4.514770e-08,8.662475e-11,3.073621e-05,3.617171e-11,1.466753e-02,0.000002,0.000004,5.180818e-07,4.516267e-09,1.818361e-13,0.000855,0.000007,0.001329,1.359238e-05,0.000002,3.774137e-09,0.000166,1.101594e-05,1.028316e-09,0.000071,4.262480e-09,0.000709,1.291416e-06,1.077862e-08,2.901390e-10,3.524639e-03,9.515134e-08,0.011547,0.000136,0.000009,4.512401e-09,2.085545e-09,1.841231e-06,0.000007,0.000154,0.000066,8.649177e-09,2.179814e-07,1.319095e-10,3.513358e-05,2.796529e-08,3.908037e-11,1.222706e-07,1.598195e-09,1.154282e-06,2.486393e-08,1.040268e-07,6.743778e-07,0.000095,4.813296e-08,0.000110,6.372211e-10,8.277178e-08,3.030944e-07,2.792225e-10,4.264747e-07,0.000060,2.206472e-08,4.751955e-04,1.805879e-06,0.000001,1.497810e-09,7.377273e-07,7.739509e-05,2.527074e-07,3.584668e-09,0.000019,3.225009e-09,7.206626e-10,6.879346e-07,0.000013,1.457757e-07,0.000081,12.507236,12.617384,12.617384,1.999384,1.889236,12.507236,1.889236,1.999384,3.569213,3.997536,-0.110148,-0.428324
1,dish_1557861216,0.000,test,cafe1,1.025138,0.000008,0.000068,0.000049,2.531807e-07,0.000004,0.000793,2.453048e-11,0.000010,0.000048,4.099626e-06,9.337625e-09,9.533460e-07,2.234901e-08,0.000021,0.000003,1.002445e-06,0.000027,2.467764e-12,2.042922e-07,0.000195,3.984670e-10,0.000670,8.282801e-08,0.000003,1.165084e-08,4.988320e-06,1.383015e-07,7.469005e-10,3.623485e-10,5.577250e-09,1.400323e-04,0.000238,0.000088,3.086594e-06,0.000017,0.000064,4.036953e-08,3.406644e-10,0.000021,0.000080,2.371435e-06,0.000874,1.702420e-05,1.081613e-05,0.000130,0.000005,2.105210e-08,0.000011,0.000009,0.000005,9.935073e-07,2.313944e-06,7.195480e-07,6.657101e-06,1.511530e-06,4.238126e-07,5.685757e-08,0.000006,1.064576e-05,3.502713e-08,2.121707e-10,3.103391e-08,5.296717e-08,6.840943e-06,4.118181e-06,1.791095e-05,0.000219,1.092374e-06,0.000080,0.000052,1.082680e-07,1.196215e-08,0.000037,4.849054e-10,0.000005,7.561895e-05,2.738368e-08,1.638611e-07,0.000006,1.033333e-07,5.089571e-11,5.500326e-06,6.375670e-04,0.000119,1.781999e-08,6.901201e-06,1.977243e-06,2.055686e-07,1.731157e-05,6.540822e-08,0.000002,4.796770e-09,0.000022,2.029012e-05,5.452864e-07,1.253916e-10,0.000560,1.057686e-08,0.000070,4.369596e-06,1.061595e-07,1.106200e-06,4.885772e-07,2.129934e-05,2.014488e-08,3.489619e-10,2.837712e-05,4.408677e-07,0.000062,3.619676e-06,0.000169,3.567937e-08,7.344974e-08,2.120137e-10,1.254462e-04,0.000007,0.001349,0.000349,0.000016,8.789895e-08,1.929147e-05,2.573321e-09,2.400313e-04,1.918648e-06,8.144424e-12,8.901064e-07,5.011475e-12,1.969034e-05,1.423345e-09,6.229192e-06,0.000078,0.000116,2.529586e-07,4.592895e-09,5.688913e-12,0.000011,0.000399,0.000093,1.012846e-07,0.000015,1.938648e-08,0.000013,2.614570e-06,1.467558e-09,0.000014,2.756734e-09,0.000028,6.887198e-08,1.580945e-08,1.192318e-08,2.626954e-07,8.517381e-05,0.000005,0.000002,0.000004,3.118906e-10,3.115805e-08,2.344037e-06,0.000004,0.000606,0.000160,2.343641e-07,3.586424e-05,9.674570e-11,1.004768e-06,2.307793e-09,2.904962e-10,1.754519e-06,9.342661e-10,8.959858e-08,3.453357e-09,6.480607e-08,5.120322e-06,0.000003,2.409789e-08,0.000138,2.307028e-08,1.436984e-09,7.274521e-09,2.252310e-11,1.642933e-06,0.000006,1.017985e-09,4.104888e-06,3.802250e-06,0.000066,1.645849e-08,3.662058e-06,4.503277e-07,3.520625e-06,3.486355e-09,0.000044,4.800576e-10,2.152842e-10,1.531195e-06,0.000007,3.537538e-04,0.000136,1.025138,2.983665,2.983665,2.983665,1.025138,1.025138,1.025138,2.983665,1.050909,8.902258,-1.958527,-7.851349
2,dish_1557862345,0.000,test,cafe1,1.074629,0.000251,0.000006,0.000220,7.137177e-07,0.000052,0.003545,8.796774e-11,0.000003,0.002151,1.097720e-04,7.518752e-07,4.193409e-06,1.070093e-07,0.000008,0.000004,8.007510e-07,0.000004,5.006764e-12,7.601964e-07,0.006537,9.366249e-10,0.000154,2.654439e-07,0.000018,3.409259e-09,2.991738e-06,1.408035e-08,6.249456e-07,1.373616e-10,3.696221e-07,2.966830e-05,0.006841,0.000228,7.715900e-06,0.003468,0.000829,3.784570e-08,4.805690e-09,0.000043,0.000159,2.478376e-06,0.003313,4.642365e-06,4.248202e-04,0.013764,0.000040,3.374327e-08,0.001180,0.000002,0.000014,1.734811e-05,2.315017e-06,2.420567e-06,1.495626e-06,1.484575e-06,2.329159e-05,1.941086e-08,0.000003,4.125135e-04,1.824228e-06,7.276798e-09,3.503172e-09,6.115845e-06,7.044785e-04,4.895959e-07,9.824815e-07,0.000015,1.654810e-03,0.001840,0.001038,1.000559e-07,3.630716e-09,0.000297,4.300828e-10,0.000321,3.293351e-04,6.758614e-06,1.040764e-07,0.000010,2.955722e-07,1.093249e-10,2.380024e-06,1.636768e-05,0.000040,2.969012e-09,9.868675e-05,2.880896e-06,5.366848e-06,4.933972e-05,1.327378e-07,0.000021,2.194425e-07,0.000464,2.338228e-04,2.758438e-06,1.211128e-09,0.000064,4.578655e-09,0.000620,1.500150e-05,5.201685e-08,1.140594e-06,2.703329e-07,3.545984e-07,4.560849e-09,2.494435e-08,1.533483e-04,1.291617e-06,0.000019,4.392153e-05,0.003220,3.711073e-08,1.371763e-09,3.444757e-10,1.031260e-04,0.000038,0.004496,0.000105,0.000002,3.054201e-07,1.161850e-06,1.079465e-06,1.854519e-04,1.705515e-06,9.462052e-12,1.033931e-06,4.057909e-10,4.795391e-07,8.147199e-10,1.379725e-05,0.000066,0.000004,2.511232e-05,3.197734e-09,1.316382e-11,0.000107,0.000011,0.000009,3.484271e-06,0.000010,9.227043e-09,0.000053,3.482519e-07,1.170639e-09,0.000008,6.666990e-09,0.000556,1.722175e-05,3.004717e-08,4.600868e-07,1.395840e-06,1.109483e-05,0.000026,0.000212,0.000069,3.815779e-09,6.007476e-08,1.167671e-05,0.000009,0.000213,0.000030,2.662222e-07,2.743711e-05,2.522572e-09,1.380320e-05,1.776814e-10,1.152692e-10,5.333744e-05,4.694339e-09,6.684232e-08,1.560715e-09,2.809420e-06,7.687498e-06,0.000174,5.981510e-08,0.000022,4.109521e-09,9.824941e-10,2.576709e-07,3.604996e-10,1.122378e-05,0.000039,1.016606e-09,1.267580e-06,2.591882e-06,0.000164,2.416496e-07,2.030833e-06,1.073947e-05,7.042350e-06,8.877369e-09,0.000265,9.985113e-07,1.876729e-10,4.616502e-06,0.000087,1.361917e-03,0.000048,1.074629,2.987030,2.987030,2.987030,1.074629,1.074629,1.074629,2.987030,1.154827,8.922346,-1.912401,-7.767519
3,dish_1557862696,3.850,test,cafe1,3.543902,0.000012,0.000091,0.000028,4.340058e-08,0.000008,0.000304,1.938500e-12,0.000008,0.049303,4.495628e-05,3.729166e-08,9.235093e-08,5.383290e-08,0.000001,0.000013,3.669011e-09,0.000002,2.786043e-14,2.136690e-08,0.000221,1.060731e-10,0.000063,1.212987e-08,0.000001,4.610664e-11,1.447503e-07,9.062444e-09,1.696717e-09,3.661115e-11,1.013219e-08,1.481113e-07,0.000034,0.000610,5.983741e-07,0.079251,0.000134,5.467767e-10,1.760638e-10,0.000002,0.000193,1.423562e-07,0.000111,5.825023e-07,4.578570e-04,0.000029,0.000004,1.137246e-09,0.000004,0.000002,0.000002,9.576995e-06,2.166625e-07,1.699308e-06,2.832527e-07,2.336659e-08,1.727323e-05,2.776544e-09,0.000024,3.245345e-05,3.216871e-08,4.537895e-10,6.243433e-10,1.562886e-07,1.081237e-02,2.369376e-08,2.370330e-08,0.000124,2.397694e-04,0.000477,0.030691,2.964078e-09,2.912922e-11,0.000048,4.914090e-10,0.000049,6.778764e-05,4.913691e-06,6.350722e-07,0.000001,1.138677e-08,4.586876e-11,1.117708e-07,1.311670e-05,0.000034,4.706790e-10,1.395193e-04,1.632322e-07,7.335174e-08,4.959731e-07,1.632972e-08,0.000159,8.319387e-09,0.000058,1.251032e-04,2.721399e-07,6.677949e-12,0.000004,1.685816e-10,0.000014,9.479227e-07,1.469072e-09,1.459385e-08,3.465625e-08,2.293409e-06,1.810471e-09,4.820157e-09,6.488919e-04,2.221370e-08,0.000002,2.213289e-05,0.000645,1.272340e-09,8.084937e-10,6.070773e-11,3.801082e-05,0.000002,0.000003,0.000002,0.000064,1.929783e-08,1.786108e-06,7.913396e-09,6.133796e-07,3.233672e-07,4.115968e-13,1.122796e-07,7.160145e-12,1.468994e-05,8.546446e-11,6.138261e-07,0.000012,0.000003,1.209146e-06,1.000396e-09,4.677922e-12,0.000101,0.000001,0.000014,2.252177e-07,0.000037,6.670089e-10,0.000338,3.670875e-08,9.577721e-11,0.000001,2.488540e-10,0.000046,1.888114e-07,2.190736e-10,7.859239e-07,8.581856e-08,1.101290e-06,0.000006,0.000095,0.000007,1.123420e-09,6.186041e-09,5.271541e-07,0.000003,0.000008,0.000015,1.434438e-08,7.555457e-04,4.278108e-10,1.052514e-07,6.765071e-13,9.117392e-12,5.901031e-06,4.945683e-10,1.134555e-09,5.887175e-10,8.736639e-09,1.017018e-05,0.000003,3.378124e-09,0.000010,5.154717e-10,3.097657e-11,2.534938e-09,8.322422e-12,2.414724e-05,0.000002,6.707739e-10,2.319802e-08,1.098868e-07,0.000045,3.541556e-08,4.461364e-07,5.211646e-08,6.635968e-06,6.769835e-09,0.000222,1.297785e-09,1.728326e-11,9.407403e-06,0.000038,3.801891e-03,0.000005,3.543902,3.917544,3.917544,0.067544,0.306098,3.543902,0.306098,0.067544,0.093696,0.004562,0.238553,0.089133
4,dish_1557862738,0.000,test,cafe1,4.563577,0.000086,0.000062,0.000468,2.328329e-04,0.000453,0.010694,2.567062e-08,0.025313,0.000154,3.459973e-05,6.381021e-05,1.874797e-02,2.766044e-05,0.002456,0.000030,6.447536e-06,0.000327,1.561469e-07,2.325325e-04,0.269503,2.540080e-08,0.004481,8.275636e-04,0.000008,1.889426e-06,9.251103e-04,7.846426e-07,5.721478e-06,3.416106e-07,9.211120e-06,3.482518e-05,0.000094,0.000529,3.557771e-04,0.000788,0.000087,2.252393e-05,4.893900e-08,0.003741,0.002770,3.872374e-04,0.001103,1.441483e-04,1.850369e-05,0.005979,0.002742,1.902804e-07,0.000273,0.003237,0.000028,3.764721e-05,1.204675e-03,2.567899e-04,3.793005e-04,1.354271e-06,1.646429e-05,1.927574e-05,0.000003,5.051767e-06,9.345172e-05,9.367308e-07,1.197192e-05,1.382062e-05,1.217889e-04,1.221148e-05,4.066757e-03,0.000997,7.099807e-05,0.026137,0.001001,1.934852e-06,2.125606e-05,0.001594,5.637310e-07,0.000405,1.334867e-04,5.022345e-07,2.695364e-05,0.008326,1.238170e-04,1.244483e-06,1.825700e-04,1.548726e-05,0.000045,2.921883e-07,8.488766e-05,2.993760e-03,1.080192e-03,2.790749e-05,6.468319e-07,0.000325,3.643007e-06,0.000588,3.804636e-05,7.027002e-05,6.502677e-07,0.010196,2.570310e-05,0.000435,3.246787e-04,3.691806e-05,9.792791e-05,3.451530e-04,2.242797e-05,3.649262e-07,3.299932e-07,3.414740e-05,4.402643e-02,0.000947,2.076387e-05,0.006166,3.402024e-04,1.175784e-05,1.462835e-06,7.632661e-05,0.060265,0.001019,0.029898,0.000046,4.303444e-04,1.017126e-05,6.981251e-06,4.993857e-05,2.965415e-04,4.323681e-08,1.535428e-05,7.268401e-10,1.018588e-03,6.762901e-06,5.761154e-03,0.000596,0.000160,5.967135e-06,2.374712e-05,1.795782e-09,0.000701,0.000510,0.000002,7.344769e-05,0.010145,1.783890e-06,0.000149,5.278907e-03,1.223107e-07,0.000483,1.391214e-05,0.013203,4.659812e-05,8.680343e-04,3.249209e-05,2.094738e-02,2.163249e-04,0.009359,0.000358,0.015514,8.667972e-07,9.635029e-06,3.555145e-03,0.039956,0.026432,0.002593,3.846659e-03,1.112848e-03,1.189054e-08,1.292707e-03,1.314733e-06,3.603700e-08,1.765373e-03,7.835270e-08,3.860595e-04,1.930732e-07,4.362710e-04,1.060006e-04,0.000036,4.359744e-06,0.002802,1.806847e-04,6.753189e-08,2.333451e-07,2.072887e-08,7.691060e-04,0.001148,3.912832e-07,7.152472e-05,9.780984e-02,0.000021,4.235904e-05,3.362240e-05,6.389380e-04,1.903416e-05,7.767943e-07,0.001004,3.225099e-06,2.230684e-07,2.086991e-04,0.003102,7.736096e-06,0.001087,4.563577,4.341109,4.341109,4.341109,4.563577,4.563577,4.563577,4.341109,20.826232,18.845227,0.222468,1.981005

['dish_id', 'total_carb', 'split', 'source_cafe', 'rgb_carb_pred', 'pred_ingr_almonds', 'pred_ingr_apple', 'pred_ingr_artichokes', 'pred_ingr_arugula', 'pred_ingr_asparagus', 'pred_ingr_avocado', 'pred_ingr_baby_carrots', 'pred_ingr_bacon', 'pred_ingr_bagels', 'pred_ingr_banana_with_peel', 'pred_ingr_basil', 'pred_ingr_beef', 'pred_ingr_beets', 'pred_ingr_bell_peppers', 'pred_ingr_berries', 'pred_ingr_black_beans', 'pred_ingr_blackberries', 'pred_ingr_blue_cheese', 'pred_ingr_blueberries', 'pred_ingr_bok_choy', 'pred_ingr_bread', 'pred_ingr_broccoli', 'pred_ingr_brown_rice', 'pred_ingr_brown_sugar', 'pred_ingr_brownies', 'pred_ingr_brussels_sprouts', 'pred_ingr_bulgur', 'pred_ingr_butter', 'pred_ingr_buttermilk', 'pred_ingr_cabbage', 'pred_ingr_caesar_dressing', 'pred_ingr_caesar_salad', 'pred_ingr_cantaloupe', 'pred_ingr_carrot', 'pred_ingr_cauliflower', 'pred_ingr_celery', 'pred_ingr_celery_root', 'pred_ingr_cereal', 'pred_ingr_chard', 'pred_ingr_chayote_squash', 'pred_ingr_cheese', 'pred_ingr_cheese_pizza', 'pred_ingr_cherry_tomatoes', 'pred_ingr_chia_seeds', 'pred_ingr_chicken', 'pred_ingr_chicken_apple_sausage', 'pred_ingr_chicken_breast', 'pred_ingr_chicken_salad', 'pred_ingr_chicken_thighs', 'pred_ingr_chickpeas', 'pred_ingr_chilaquiles', 'pred_ingr_chili', 'pred_ingr_chive', 'pred_ingr_cilantro', 'pred_ingr_cod', 'pred_ingr_cookies', 'pred_ingr_corn', 'pred_ingr_corn_on_the_cob', 'pred_ingr_cottage_cheese', 'pred_ingr_country_rice', 'pred_ingr_couscous', 'pred_ingr_cranberries', 'pred_ingr_cream', 'pred_ingr_cream_cheese', 'pred_ingr_croutons', 'pred_ingr_cucumbers', 'pred_ingr_deprecated', 'pred_ingr_egg_whites', 'pred_ingr_eggplant', 'pred_ingr_eggs', 'pred_ingr_feta_cheese', 'pred_ingr_figs', 'pred_ingr_fish', 'pred_ingr_flour', 'pred_ingr_fried_rice', 'pred_ingr_frozen_yogurt', 'pred_ingr_fruit_salad', 'pred_ingr_garden_salad', 'pred_ingr_garlic', 'pred_ingr_ginger', 'pred_ingr_goat_cheese', 'pred_ingr_granola', 'pred_ingr_grapefruit_juice', 'pred_ingr_grapes', 'pred_ingr_greek_salad', 'pred_ingr_greek_yogurt', 'pred_ingr_green_beans', 'pred_ingr_green_onions', 'pred_ingr_grilled_chicken', 'pred_ingr_ground_turkey', 'pred_ingr_hash_browns', 'pred_ingr_hominy', 'pred_ingr_honeydew_melons', 'pred_ingr_ice_cream_cones', 'pred_ingr_jalapenos', 'pred_ingr_jicama', 'pred_ingr_kale', 'pred_ingr_ketchup', 'pred_ingr_kimchi', 'pred_ingr_lemon_juice', 'pred_ingr_lentils', 'pred_ingr_lettuce', 'pred_ingr_lime', 'pred_ingr_mandarin_oranges', 'pred_ingr_mangos', 'pred_ingr_mayonnaise', 'pred_ingr_milk', 'pred_ingr_millet', 'pred_ingr_mixed_greens', 'pred_ingr_mozzarella_cheese', 'pred_ingr_mushroom', 'pred_ingr_mustard', 'pred_ingr_mustard_greens', 'pred_ingr_nopales', 'pred_ingr_oatmeal', 'pred_ingr_olive_oil', 'pred_ingr_olives', 'pred_ingr_onions', 'pred_ingr_orange', 'pred_ingr_orange_juice', 'pred_ingr_orange_with_peel', 'pred_ingr_oregano', 'pred_ingr_parmesan_cheese', 'pred_ingr_parsley', 'pred_ingr_parsnips', 'pred_ingr_pasta', 'pred_ingr_pasta_salad', 'pred_ingr_pears', 'pred_ingr_pecans', 'pred_ingr_pepper', 'pred_ingr_pepperoni', 'pred_ingr_pepperoni_pizza', 'pred_ingr_pesto', 'pred_ingr_pickles', 'pred_ingr_pilaf', 'pred_ingr_pineapple', 'pred_ingr_pizza', 'pred_ingr_plate_only', 'pred_ingr_pork', 'pred_ingr_potatoes', 'pred_ingr_pumpkin_seeds', 'pred_ingr_quinoa', 'pred_ingr_radishes', 'pred_ingr_raisins', 'pred_ingr_raspberries', 'pred_ingr_rice_noodles', 'pred_ingr_roasted_potatoes', 'pred_ingr_rosemary', 'pred_ingr_salmon', 'pred_ingr_salsa', 'pred_ingr_salt', 'pred_ingr_sandwiches', 'pred_ingr_sausage', 'pred_ingr_scrambled_eggs', 'pred_ingr_shallots', 'pred_ingr_snow_peas', 'pred_ingr_sour_cream', 'pred_ingr_soy_sauce', 'pred_ingr_spinach_cooked', 'pred_ingr_spinach_raw', 'pred_ingr_squash', 'pred_ingr_steak', 'pred_ingr_strawberries', 'pred_ingr_succotash', 'pred_ingr_sugar', 'pred_ingr_sun_dried_tomatoes', 'pred_ingr_sunflower_seeds', 'pred_ingr_sweet_potato', 'pred_ingr_syrup', 'pred_ingr_tatsoi', 'pred_ingr_tempeh', 'pred_ingr_thyme', 'pred_ingr_toast', 'pred_ingr_tofu', 'pred_ingr_tomatillo', 'pred_ingr_tomatoes', 'pred_ingr_tortilla', 'pred_ingr_tortilla_chips', 'pred_ingr_tuna', 'pred_ingr_tuna_salad', 'pred_ingr_turkey_bacon', 'pred_ingr_turnips', 'pred_ingr_vegetable_oil', 'pred_ingr_vinaigrette', 'pred_ingr_vinegar', 'pred_ingr_waffles', 'pred_ingr_walnuts', 'pred_ingr_watermelon', 'pred_ingr_wheat_berry', 'pred_ingr_wheat_bread', 'pred_ingr_white_beans', 'pred_ingr_white_rice', 'pred_ingr_white_wine', 'pred_ingr_wild_rice', 'pred_ingr_wine', 'pred_ingr_yam', 'pred_ingr_yogurt', 'pred_ingr_zucchini', 'rgb_only_pred', 'model22_pred', 'final_pred', 'abs_error', 'abs_error_rgb_only', 'old_final_pred_wrong', 'old_abs_error_wrong', 'abs_error_model22', 'squared_error_rgb_only', 'squared_error_model22', 'abs_error_improvement_model22_vs_rgb', 'squared_error_improvement_model22_vs_rgb']

Loading prediction CSV

In [ ]:
target_col = "total_carb"
rgb_col = "rgb_only_pred"
model22_col = "model22_pred"

required_cols = ["dish_id", target_col, rgb_col, model22_col]

missing_cols = [col for col in required_cols if col not in df.columns]

if missing_cols:
    raise ValueError(f"Missing columns in CSV: {missing_cols}")

# Absolute errors
df["rgb_abs_error"] = (df[rgb_col] - df[target_col]).abs()
df["model22_abs_error"] = (df[model22_col] - df[target_col]).abs()

# Error improvement: positive means Model 22 improved compared to RGB-only / Model 3 V3
df["abs_error_improvement"] = df["rgb_abs_error"] - df["model22_abs_error"]

# Percentage errors
df["rgb_percentage_error"] = np.where(
    df[target_col] > 0,
    (df["rgb_abs_error"] / df[target_col]) * 100,
    np.nan
)

df["model22_percentage_error"] = np.where(
    df[target_col] > 0,
    (df["model22_abs_error"] / df[target_col]) * 100,
    np.nan
)

# Percentage error improvement
df["percentage_error_improvement"] = df["rgb_percentage_error"] - df["model22_percentage_error"]

display_cols = [
    "dish_id",
    target_col,
    rgb_col,
    model22_col,
    "rgb_abs_error",
    "model22_abs_error",
    "abs_error_improvement",
    "rgb_percentage_error",
    "model22_percentage_error",
    "percentage_error_improvement",
]

display(df[display_cols].head())

,dish_id,total_carb,rgb_only_pred,model22_pred,rgb_abs_error,model22_abs_error,abs_error_improvement,rgb_percentage_error,model22_percentage_error,percentage_error_improvement
0,dish_1556575327,10.618,12.507236,12.617384,1.889236,1.999384,-0.110148,17.792767,18.830138,-1.037371
1,dish_1557861216,0.000,1.025138,2.983665,1.025138,2.983665,-1.958527,NaN,NaN,NaN
2,dish_1557862345,0.000,1.074629,2.987030,1.074629,2.987030,-1.912401,NaN,NaN,NaN
3,dish_1557862696,3.850,3.543902,3.917544,0.306098,0.067544,0.238553,7.950587,1.754400,6.196187
4,dish_1557862738,0.000,4.563577,4.341109,4.563577,4.341109,0.222468,NaN,NaN,NaN

In [ ]:
def create_top10_table(data, ranking_col, title):
    print("=" * 120)
    print(title)
    print("=" * 120)

    table_cols = [
        "dish_id",
        target_col,
        rgb_col,
        model22_col,
        "rgb_abs_error",
        "model22_abs_error",
        "abs_error_improvement",
        "rgb_percentage_error",
        "model22_percentage_error",
        "percentage_error_improvement",
    ]

    best_10 = data.sort_values(ranking_col, ascending=True).head(10).copy()
    worst_10 = data.sort_values(ranking_col, ascending=False).head(10).copy()

    print("\nTop 10 best Model 22 predictions:")
    display(best_10[table_cols].round(2))

    print("\nTop 10 worst Model 22 predictions:")
    display(worst_10[table_cols].round(2))

    return best_10, worst_10

Version 1 Top 10 by absolute error

In [ ]:
best_abs, worst_abs = create_top10_table(
    data=df,
    ranking_col="model22_abs_error",
    title="Top 10 best and worst Model 22 predictions based on absolute error"
)

========================================================================================================================
Top 10 best and worst Model 22 predictions based on absolute error
========================================================================================================================

Top 10 best Model 22 predictions:

,dish_id,total_carb,rgb_only_pred,model22_pred,rgb_abs_error,model22_abs_error,abs_error_improvement,rgb_percentage_error,model22_percentage_error,percentage_error_improvement
476,dish_1566849987,20.53,20.66,20.54,0.12,0.01,0.11,0.59,0.05,0.55
173,dish_1560526530,26.79,25.81,26.82,0.98,0.04,0.94,3.66,0.14,3.53
3,dish_1557862696,3.85,3.54,3.92,0.31,0.07,0.24,7.95,1.75,6.20
141,dish_1559850283,10.67,9.98,10.76,0.69,0.09,0.60,6.48,0.88,5.60
266,dish_1562691000,27.18,25.28,27.05,1.90,0.13,1.77,6.98,0.49,6.50
504,dish_1568401233,32.33,30.11,32.47,2.22,0.14,2.09,6.88,0.43,6.45
339,dish_1563984140,3.30,1.83,3.16,1.47,0.15,1.33,44.63,4.39,40.23
62,dish_1558461792,34.50,31.89,34.65,2.61,0.15,2.46,7.57,0.43,7.14
393,dish_1565035715,3.51,2.62,3.35,0.89,0.16,0.73,25.30,4.53,20.76
455,dish_1566502437,3.82,2.39,3.99,1.44,0.16,1.28,37.63,4.26,33.37

Top 10 worst Model 22 predictions:

,dish_id,total_carb,rgb_only_pred,model22_pred,rgb_abs_error,model22_abs_error,abs_error_improvement,rgb_percentage_error,model22_percentage_error,percentage_error_improvement
178,dish_1560801020,61.69,27.43,29.51,34.26,32.18,2.08,55.53,52.17,3.36
149,dish_1560367952,45.96,13.09,14.42,32.87,31.54,1.33,71.51,68.63,2.88
179,dish_1560801041,63.25,29.55,32.21,33.70,31.04,2.66,53.28,49.07,4.21
177,dish_1560800988,61.25,28.56,31.14,32.69,30.11,2.59,53.38,49.15,4.22
150,dish_1560367980,47.24,16.45,17.53,30.80,29.71,1.08,65.18,62.89,2.29
313,dish_1563478751,54.13,25.82,26.63,28.31,27.50,0.82,52.31,50.80,1.51
247,dish_1562009934,62.24,33.66,35.61,28.59,26.64,1.95,45.93,42.79,3.13
318,dish_1563551220,79.79,52.11,54.64,27.68,25.15,2.53,34.70,31.52,3.18
446,dish_1566328805,85.05,57.37,60.60,27.69,24.45,3.24,32.55,28.75,3.80
454,dish_1566501594,54.28,29.89,29.90,24.39,24.38,0.01,44.93,44.91,0.01

Version 2 Top 10 by percentage error

In [ ]:
df_pct = df.dropna(subset=["model22_percentage_error"]).copy()

best_pct, worst_pct = create_top10_table(
    data=df_pct,
    ranking_col="model22_percentage_error",
    title="Top 10 best and worst Model 22 predictions based on percentage error"
)

========================================================================================================================
Top 10 best and worst Model 22 predictions based on percentage error
========================================================================================================================

Top 10 best Model 22 predictions:

,dish_id,total_carb,rgb_only_pred,model22_pred,rgb_abs_error,model22_abs_error,abs_error_improvement,rgb_percentage_error,model22_percentage_error,percentage_error_improvement
476,dish_1566849987,20.53,20.66,20.54,0.12,0.01,0.11,0.59,0.05,0.55
173,dish_1560526530,26.79,25.81,26.82,0.98,0.04,0.94,3.66,0.14,3.53
504,dish_1568401233,32.33,30.11,32.47,2.22,0.14,2.09,6.88,0.43,6.45
62,dish_1558461792,34.50,31.89,34.65,2.61,0.15,2.46,7.57,0.43,7.14
266,dish_1562691000,27.18,25.28,27.05,1.90,0.13,1.77,6.98,0.49,6.50
238,dish_1561739238,37.56,35.07,37.76,2.48,0.21,2.28,6.61,0.55,6.06
279,dish_1562774180,24.86,22.82,24.68,2.04,0.18,1.86,8.21,0.72,7.49
288,dish_1562788601,48.77,45.67,49.12,3.09,0.36,2.73,6.34,0.73,5.61
135,dish_1559849053,25.23,24.02,25.02,1.21,0.21,1.00,4.80,0.83,3.97
141,dish_1559850283,10.67,9.98,10.76,0.69,0.09,0.60,6.48,0.88,5.60

Top 10 worst Model 22 predictions:

,dish_id,total_carb,rgb_only_pred,model22_pred,rgb_abs_error,model22_abs_error,abs_error_improvement,rgb_percentage_error,model22_percentage_error,percentage_error_improvement
354,dish_1564427406,0.14,2.27,3.60,2.14,3.47,-1.33,1583.64,2568.83,-985.19
310,dish_1563389548,0.19,5.01,4.62,4.82,4.43,0.39,2482.86,2281.67,201.19
28,dish_1558110335,0.10,0.73,1.85,0.63,1.76,-1.12,647.93,1791.10,-1143.17
41,dish_1558373074,0.43,4.33,6.99,3.90,6.57,-2.66,916.15,1541.52,-625.37
13,dish_1557937427,0.20,1.19,3.10,0.98,2.90,-1.92,480.89,1420.56,-939.67
381,dish_1565020755,0.11,-0.02,1.58,0.13,1.47,-1.34,114.32,1308.91,-1194.59
58,dish_1558461431,0.18,1.16,2.48,0.98,2.30,-1.32,542.26,1277.84,-735.58
330,dish_1563897938,0.14,0.43,1.79,0.29,1.65,-1.36,206.93,1181.84,-974.91
306,dish_1563294987,0.25,1.72,3.20,1.47,2.95,-1.48,582.37,1169.81,-587.43
417,dish_1565811000,0.72,8.93,9.04,8.21,8.32,-0.11,1140.77,1155.96,-15.19

Version 3 Top 10 by percentage error after removing dishes under 5g carbohydrates

In [ ]:
MIN_CARB_THRESHOLD = 5.0

df_pct_min5 = df_pct[df_pct[target_col] >= MIN_CARB_THRESHOLD].copy()

print("Original test set size:", len(df))
print("Test set size after removing dishes below 5g carbohydrates:", len(df_pct_min5))
print("Removed dishes:", len(df) - len(df_pct_min5))

best_pct_min5, worst_pct_min5 = create_top10_table(
    data=df_pct_min5,
    ranking_col="model22_percentage_error",
    title="Top 10 best and worst Model 22 predictions based on percentage error, excluding dishes below 5g carbohydrates"
)

Original test set size: 507
Test set size after removing dishes below 5g carbohydrates: 380
Removed dishes: 127
========================================================================================================================
Top 10 best and worst Model 22 predictions based on percentage error, excluding dishes below 5g carbohydrates
========================================================================================================================

Top 10 best Model 22 predictions:

,dish_id,total_carb,rgb_only_pred,model22_pred,rgb_abs_error,model22_abs_error,abs_error_improvement,rgb_percentage_error,model22_percentage_error,percentage_error_improvement
476,dish_1566849987,20.53,20.66,20.54,0.12,0.01,0.11,0.59,0.05,0.55
173,dish_1560526530,26.79,25.81,26.82,0.98,0.04,0.94,3.66,0.14,3.53
504,dish_1568401233,32.33,30.11,32.47,2.22,0.14,2.09,6.88,0.43,6.45
62,dish_1558461792,34.50,31.89,34.65,2.61,0.15,2.46,7.57,0.43,7.14
266,dish_1562691000,27.18,25.28,27.05,1.90,0.13,1.77,6.98,0.49,6.50
238,dish_1561739238,37.56,35.07,37.76,2.48,0.21,2.28,6.61,0.55,6.06
279,dish_1562774180,24.86,22.82,24.68,2.04,0.18,1.86,8.21,0.72,7.49
288,dish_1562788601,48.77,45.67,49.12,3.09,0.36,2.73,6.34,0.73,5.61
135,dish_1559849053,25.23,24.02,25.02,1.21,0.21,1.00,4.80,0.83,3.97
141,dish_1559850283,10.67,9.98,10.76,0.69,0.09,0.60,6.48,0.88,5.60

Top 10 worst Model 22 predictions:

,dish_id,total_carb,rgb_only_pred,model22_pred,rgb_abs_error,model22_abs_error,abs_error_improvement,rgb_percentage_error,model22_percentage_error,percentage_error_improvement
83,dish_1558639482,6.38,12.78,13.91,6.40,7.53,-1.12,100.36,117.97,-17.61
421,dish_1565811139,9.06,20.05,19.07,10.99,10.01,0.98,121.31,110.44,10.87
420,dish_1565811091,9.06,19.27,18.48,10.21,9.42,0.80,112.75,103.93,8.81
167,dish_1560456370,14.92,28.19,30.43,13.27,15.51,-2.24,88.94,103.93,-14.99
248,dish_1562085672,19.46,37.61,39.37,18.16,19.91,-1.76,93.31,102.33,-9.02
188,dish_1560975601,17.95,32.45,35.50,14.51,17.56,-3.05,80.84,97.83,-16.99
99,dish_1558718680,5.22,9.53,10.25,4.31,5.03,-0.72,82.46,96.26,-13.81
479,dish_1566850142,9.05,15.73,16.53,6.68,7.48,-0.80,73.75,82.64,-8.89
464,dish_1566589967,13.40,23.72,24.15,10.32,10.75,-0.43,76.98,80.21,-3.23
303,dish_1563221054,6.51,11.13,11.65,4.62,5.14,-0.52,70.90,78.94,-8.04